language: python
python:
  - "3.6"
install: "pip install -r test-requirements.txt --use-mirrors"
# command to run tests
script: python setup.py install && nosetests tests/unit tests/acceptance

branches:
  only:
    - master
    - develop

services:
  - elasticsearch
